
export const episodesS2 = [
    {number: "1",
    season: "2",
    title: "Tony and Maxxie", 
    air_date: "11-02-2008",
    summary: "Six months on, Tony is still recovering from injuries sustained in the last series. He suffers from subdural hematoma leading to learning difficulties, amnesia, a lack of fine motor skills and personality changes. His mother slips into depression while his father struggles to control his frustration with the change in family dynamic. Sid cannot bear to see Tony in his condition, and Cassie moves up to Scotland. Effy steps up to take care of Tony. Maxxie is confronted by homophobic youths on his estate and by his father, who is keen for him to stay in college rather than become a dancer. The gang attend a rave, during which Tony has a panic attack and runs out. Maxxie runs out to look for him but is ambushed by the homophobes, one of which catches Maxxie and wrestles him to the ground and tries to kiss him. Maxxie succumbs and the two make out. Tony finds Michelle and Sid talking about him and assures them he will regain his lost memories.",
    characters_actors: [
        {character:"Tony Stonem", actor: "Nicholas Hoult"}, 
        {character: "Sid Jenkins", actor: "Mike Bailey"}, 
        {character: "Chris Miles", actor: "Joe Dempsie"}, 
        {character: "Maxxie Oliver", actor: "Mitch Hewer"}, 
        {character: "Anwar Kharral", actor: "Dev Patel"}, 
        {character: "Jal Fazer", actor: "Larissa Wilson"}, 
        {character: "Michelle Richardson", actor: "April Pearson"}, 
        {character: "Cassie Ainsworth", actor: "Hannah Murray"}, 
        {character: "Effy Stonem", actor: "Kaya Scodelario"},
        {character: "Lucy Sketch", actor: "Aimee-Ffion Edwards"}
    ],
    author: "Bryan Elsley",
    director: "Aysha Rafaele"},

    {number: "2",
    season: "2",
    title: "Sketch", 
    air_date: "18-02-2008",
    summary: "Sketch is a young carer for her disabled mother and is obsessed with Maxxie. Her schemes to make him fall in love with her endanger the college's production of \"Osama: The Musical\" and lead her to lie about the drama teacher molesting her to get a role in the play. Sketch befriends Michelle after seeing her fail to seduce a hesitant Tony, who suffers from erectile dysfunction following his injury. Sketch drugs Michelle to take her part in the play as Maxxie's love interest. The two kiss on stage as written, but Maxxie tells Sketch that he felt nothing. She slaps him and bursts into tears on stage. That night, she has sex with his best friend Anwar.",
    characters_actors: [
        {character:"Tony Stonem", actor: "Nicholas Hoult"}, 
        {character: "Sid Jenkins", actor: "Mike Bailey"}, 
        {character: "Chris Miles", actor: "Joe Dempsie"}, 
        {character: "Maxxie Oliver", actor: "Mitch Hewer"}, 
        {character: "Anwar Kharral", actor: "Dev Patel"}, 
        {character: "Jal Fazer", actor: "Larissa Wilson"}, 
        {character: "Michelle Richardson", actor: "April Pearson"}, 
        {character: "Cassie Ainsworth", actor: "Hannah Murray"}, 
        {character: "Effy Stonem", actor: "Kaya Scodelario"},
        {character: "Lucy Sketch", actor: "Aimee-Ffion Edwards"}
    ],
    author: "Jack Thorne",
    director: "Aysha Rafaele"},
    
    {number: "3",
    season: "2",
    title: "Sid", 
    air_date: "25-02-2008",
    summary: "Sid is in despair. Tony is a shadow of his former self and Cassie has settled down in Scotland. Sid and his father, Mark, are visited by Mark's father, brother, and nephews, who constantly belittle Mark and Sid. Mark persuades Sid’s mother to move back home for a day and pretend as though they were not separated. Sid breaks up with Cassie over a misunderstanding. Mark finally takes a stand against his father and brother and orders them to leave. He regrets being cruel to Sid, realizing that's how his father always treated him. He dies of an apparent heart attack that night and Sid discovers his body the next morning. Sid can't come to terms with it and leaves him where he's sitting, telling no one. Tony approaches him, saying people told him they were best friends. They attend a Crystal Castles gig where Sid opens up to Tony about his problems. Tony and Sid go back to Sid's house where Mark's body is still in the chair. Sid asks if this (his father's death and his breakup) is real. Sid calls his mother, then he boards a train.",
    characters_actors: [
        {character:"Tony Stonem", actor: "Nicholas Hoult"}, 
        {character: "Sid Jenkins", actor: "Mike Bailey"}, 
        {character: "Chris Miles", actor: "Joe Dempsie"}, 
        {character: "Maxxie Oliver", actor: "Mitch Hewer"}, 
        {character: "Anwar Kharral", actor: "Dev Patel"}, 
        {character: "Jal Fazer", actor: "Larissa Wilson"}, 
        {character: "Michelle Richardson", actor: "April Pearson"}, 
        {character: "Cassie Ainsworth", actor: "Hannah Murray"}, 
        {character: "Effy Stonem", actor: "Kaya Scodelario"},
        {character: "Lucy Sketch", actor: "Aimee-Ffion Edwards"}
    ],
    author: "Bryan Elsley",
    director: "Simon Massey"},
];